device: cuda
output:
  save_results: True
  overlay: True
  save_path: results/qualitative_ade_gt # change dir according to vocabulary type
sam:
  model_type: vit_h
  weight_path: checkpoints/sam_vit_h_4b8939.pth
clip:
  model_type: ViT-B/16
  weight_path: checkpoints/clip_b16_grit+mim_fultune_4xe.pth
dataset:
  name: qualitative # coco , ade20k_sem_seg_val, qualitative
  root: None
  vocabulary: image_caption # [image_caption, coco_gt, ade_caption] Can change with any of these
dataloader:
  batch_size: 1
  shuffle: False