device: cuda
save_results: True
overlay: True
sam:
  model_type: vit_h
  weight_path: checkpoints/sam_vit_h_4b8939.pth
clip:
  model_type: ViT-B/16
  weight_path: checkpoints/clip_b16_grit+mim_fultune_4xe.pth
dataset:
  name: coco # ade20kfull, ade20k, qualitative
  root: datasets/coco
  vocabulary: coco_gt # [image_caption, ade_gt, ade_caption]
dataloader:
  batch_size: 1
  shuffle: False