device: cuda
output:
  save_predictions: True
  overlay: True
  save_path: results/qualitative_cap_sam
  save_results: output/sam/qualitative_cap_sam
sam:
  model_type: vit_h
  weight_path: checkpoints/sam_vit_h_4b8939.pth
  post_process: blurred_masks # blurred_masks, red_circle_masks, bbox_masks, black_background_masks, none
clip:
  model_type: ViT-B/16
  weight_path: checkpoints/clip_b16_grit+mim_fultune_4xe.pth
dataset:
  name: qualitative # coco , ade20k_sem_seg_val, qualitative
  root: datasets/ADE20K_2021_17_01/images_detectron2/validation
  vocabulary: image_caption # [image_caption, coco_gt, ade_caption]
dataloader:
  batch_size: 1
  shuffle: False

