device: cuda
output:
  save_results: True
  overlay: True
  save_path: results/ade_gt
sam:
  model_type: vit_h
  weight_path: checkpoints/sam_vit_h_4b8939.pth
  postprocessing: black_background_mask # blurred_masks, red_circle_masks, bbox_masks, black_background_masks, none
clip:
  model_type: ViT-B/16
  weight_path: checkpoints/clip_b16_grit+mim_fultune_4xe.pth
dataset:
  name: ade20k_full_sem_seg_val # coco , ade20k_sem_seg_val, qualitative
  root: datasets/ADE20K_2021_17_01
  vocabulary: ade_gt # [image_caption, coco_gt, ade_caption]
dataloader:
  batch_size: 1
  shuffle: False

